### PR TITLE
Fix for failure to apply when the patch is in unified format and has multiple diffs.

### PR DESCRIPTION
**Pull request by hgontijo**
How to generate a diff in Unified Format (http://en.wikipedia.org/wiki/Diff_utility#Unified_format):
- gnu diff
  $ diff -urNp FILES
- review board / rbt diff - https://www.reviewboard.org/docs/rbtools/dev/rbt/commands/diff/#rbt-diff
  $ rbt diff [revisions]
- review board api - https://www.reviewboard.org/docs/manual/2.0/webapi/2.0/resources/#diffs

### CODE REVIEW

**Comment by jmherbst** [comment]
Any reason this hasn't been merged?

**Comment by hgontijo** [comment]
Ping.

**Comment by hgontijo** [comment]
@kohsuke, could this PR be merged?

**Comment by hgontijo** [comment]
@kohsuke, could you please take a look on this PR?

**Pull request merged**
